# Generated by Django 2.2.7 on 2019-11-15 14:04

from django.db import migrations
import main.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.models.user.UserManager()),
            ],
        ),
    ]
